In [10]:
# imports

from scipy.io import loadmat
import numpy as np

In [11]:
# pré-carregamento

avi_data = list()
for i in range(1,6):
    avi_data.append(loadmat(f"../dataset/multi/Sub{i}_1_multitarget.mat"))

In [12]:
# extração direta dos dados

X = [d['Data'][0][0][7] for d in avi_data]
y = [d['Data'][0][0][8][0] for d in avi_data]

print("Divisão dos dados:")
for data in X:
    print(data.shape, data.T.shape)

print("\nDivisão dos rótulos (sequências):")
for data in y:
    print(data)

Divisão dos dados:
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)

Divisão dos rótulos (sequências):
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]


In [13]:
reshape_X = np.array([np.transpose(data) for data in X])
print(reshape_X.shape)

(5, 10, 8192)
